server:
  port: 8761
spring:
  application:
    name: mamba-discovery-service
  security:
    user:
      name: mamba
      password: mamba
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
        - VM.*
      preferredNetworks:
        - 192.168
# 注册中心配置
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    # 表明该服务不会向Eureka Server注册自己的信息
    register-with-eureka: false
    # 表明该服务不会向Eureka Server获取注册信息
    fetch-registry: false
    service-url:
      # Eureka Server 注册中心的地址，用于client 与 server进行交流
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
# 日志输出级别
logging:
  level:
    org.springframework: DEBUG